# Update Frontend to use Azure Backend API

param(
    [Parameter(Mandatory=$false)]
    [string]$ApiUrl
)

# If no API URL provided, try to read from backend deployment config
if (-not $ApiUrl) {
    if (Test-Path "backend-deployment-config.json") {
        $config = Get-Content "backend-deployment-config.json" | ConvertFrom-Json
        $ApiUrl = $config.apiUrl
        Write-Host "📖 Using API URL from backend-deployment-config.json" -ForegroundColor Cyan
    } else {
        Write-Host "❌ No API URL provided and no backend-deployment-config.json found" -ForegroundColor Red
        Write-Host "Usage: .\update_frontend_api.ps1 -ApiUrl 'https://your-api-url'" -ForegroundColor Yellow
        exit 1
    }
}

Write-Host "🔄 Updating frontend to use Azure backend API..." -ForegroundColor Cyan

# Update the azure-api-config.js file
$configPath = "frontend_new/azure-api-config.js"
$configContent = @"
// Azure API Configuration
// This file is automatically generated during deployment
// Update this with your Azure Container Apps backend URL

window.API_URL = '$ApiUrl';
"@

$configContent | Out-File $configPath -Encoding UTF8

Write-Host "✅ Frontend updated with API URL: $ApiUrl" -ForegroundColor Green
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Cyan
Write-Host "1. Test locally: Open frontend_new/index.html in browser" -ForegroundColor White
Write-Host "2. Deploy to Azure:" -ForegroundColor White
Write-Host "   cd frontend_new" -ForegroundColor Gray
Write-Host "   swa deploy . --env production" -ForegroundColor Gray
Write-Host ""
